apiv1/urls.py
from django.conf.urls import url

from . import views
from .models import SLUG_LENGTH

SLUG_REGEX = "[a-zA-Z0-9]{{1,{0}}}".format(SLUG_LENGTH)

app_name = 'apiv1'
urlpatterns = [
    url(r'^(?P<slug>{})$'.format(SLUG_REGEX), views.slug, name='slug'),
    url(r'^(?P<slug>{})/detail/$'.format(SLUG_REGEX), views.detail, name='detail'),
    url(r'^create/$', views.create, name='create'),
]

shortener/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/v1/', include('apiv1.urls')),
    url(r'^', include('web_front.urls')),
]

web_front/urls.py
from django.views.generic import RedirectView
from django.conf.urls import url

from . import views
from apiv1.urls import SLUG_REGEX


app_name = 'web_front'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^custom/$', views.custom, name='custom'),
    url(r'^recent$', RedirectView.as_view(url='recent/')),
    url(r'^recent/$', views.recent, name='recent'),
    url(r'^(?P<slug>{})/?$'.format(SLUG_REGEX), views.slug, name='slug'),
    url(r'^(?P<slug>{})/detail/$'.format(SLUG_REGEX), views.detail, name='detail'),
]

apiv1/models.py
from random import SystemRandom
from string import ascii_letters, digits
from django.db import models

SLUG_LENGTH = 8


class Slug(models.Model):
    """
    Database table that will store our slugs
    and related helper functions.
    """
    site_title = models.CharField(max_length=200)
    target_url = models.CharField(max_length=200, unique=True, db_index=True)
    slug = models.CharField(max_length=SLUG_LENGTH, unique=True, db_index=True)
    create_date = models.DateTimeField(auto_now=False, auto_now_add=True)
    hit_count = models.IntegerField(default=0)
    creator_ip = models.GenericIPAddressField()

    def __str__(self):
        """
        Giving this model a descriptive string representation.
        :return: String descriptor
        """
        return "{} - {}".format(self.site_title, self.slug)

    def save(self, *args, **kwargs):
        """
        Helper function to save the models to the database.
        """
        self.slug = self.slug or self.new_slug()
        super(Slug, self).save(*args, **kwargs)

    def new_slug(self):
        """
        Helper function to get a new slug if one is not provided.
        :return: a unique, random slug of length SLUG_LENGTH
        """
        slug = self._generate_random_slug()
        if Slug.objects.filter(slug=slug).count() > 0:
            slug = self.new_slug()
        return slug

    def get_dict(self):
        """
        Helper function to return a dictionary of all values
        associated with a model.
        :return: Dict object
        """
        payload = {}
        payload['site_title'] = self.site_title
        payload['target_url'] = self.target_url
        payload['slug'] = self.slug
        payload['create_date'] = self.create_date.isoformat()
        payload['hit_count'] = self.hit_count
        return payload

    def _generate_random_slug(self):
        """
        Helper function to generate a random slug of length SLUG_LENGTH.
        :return: random slug of length SLUG_LENGTH
        """
        size = SLUG_LENGTH
        chars = ascii_letters + digits
        return ''.join(SystemRandom().choice(chars) for _ in range(size))

web_front/forms.py
from django import forms


class StandardCreateForm(forms.Form):
    target_url = forms.URLField(label='target url')


class CustomCreateForm(forms.Form):
    target_url = forms.URLField(label='target url')
    slug = forms.CharField(label='slug', min_length=2, max_length=8,
                           required=True, strip=True)

apiv1/views.py
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.views.defaults import bad_request
from django.http import HttpResponse

from .functions import create_new_slug, get_slug_json, get_detail_json

import json


def slug(request, slug):
    """
    View that reuturns a target_url for a given slug
    :return: HttpResponse JSON object
    """
    return HttpResponse(get_slug_json(slug))


def detail(request, slug):
    """
    View that returns a JSON of the full information
    of a given slug.
    :return: HttpResponse JSON object
    """
    return HttpResponse(get_detail_json(slug))


# Need CSRF exempt decorator to allow requests without CSRF tokens
@require_POST
@csrf_exempt
def create(request):
    """
    View that will create a new slug and return new slug
    :return: HttpResponse JSON object
    """
    # Try/Except to catch malformed request bodies elegantly
    try:
        body = json.loads(request.body.decode())
        if 'target_url' not in body.keys():
            raise Exception('Body was not valid JSON')

        response = create_new_slug(request, body)

    except Exception as e:
        return bad_request(request, e)

    if response.get('created'):
        return HttpResponse(json.dumps(response))
    else:
        return HttpResponse(json.dumps(response), status=409)

web_front/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponseRedirect

from apiv1.models import Slug
from apiv1.functions import create_new_slug

from .forms import StandardCreateForm, CustomCreateForm


def slug(request, slug):
    """
    Receives slug from URI, returns 301 redirect to
    target URL to browser.  If slug does not exist,
    returns 404
    :return: redirect to target URL or 404
    """
    target_url = get_object_or_404(Slug, slug__exact=slug)
    target_url.hit_count += 1
    target_url.save()
    return redirect(target_url.target_url)


def index(request):
    """
    Landing page for web front.  Will be a form with a
    text box and submit button to create a randomly-generated
    slug.
    """
    if request.method == 'POST':
        # Create a form instance and populate it with data from the request
        form = StandardCreateForm(request.POST)
        if form.is_valid():
            body = {"target_url": form.cleaned_data.get("target_url")}
            response = create_new_slug(request, body)
            return HttpResponseRedirect('/{}/detail/'.format(response.get('slug')))

    # If a GET, create a blank form
    else:
        form = StandardCreateForm()

    return render(request, 'web_front/create.html', {'form': form})


def custom(request):
    """
    Form with 2 text boxes and a submit button.  Users can
    create a customized slug here.
    """
    if request.method == 'POST':
        # Create a form instance and populate it with data from the request
        form = CustomCreateForm(request.POST)
        if form.is_valid():
            body = {"target_url": form.cleaned_data.get("target_url"),
                    "slug": form.cleaned_data.get("slug")}
            print(body)
            response = create_new_slug(request, body)
            return HttpResponseRedirect('/{}/detail/'.format(response.get('slug')))

    # If a GET, create a blank form
    else:
        form = CustomCreateForm()

    return render(request, 'web_front/create.html', {'form': form})


def detail(request, slug):
    """
    Page where users can see detailed information about a
    slug before visiting the target_url.
    """
    slug_obj = get_object_or_404(Slug, slug__exact=slug)
    return render(request, 'web_front/detail.html', {'slug': slug_obj})


def recent(request):
    """
    Page where users can see the X most recently created
    slugs and target URLs.
    """
    slug_list = Slug.objects.order_by('-create_date')[:5]
    return render(request, 'web_front/recent.html', {'slug_list': slug_list, })

web_front/templates/web_front/base.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Headers and Formalities -->
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>TxMoo.se Shortener</title>

        <!-- CSS  -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
        <link rel="stylesheet" type="text/css"href="{% static 'material/fonts/material-design-icons/material-icons.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'material/css/materialize.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'material/css/materialize.forms.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'material/css/jquery.datetimepicker.css' %}"/>
        <script type="text/javascript" src="{% static 'material/js/jquery-2.2.0.js' %}"></script>
    </head>
    <body>
        <!-- Nav Bar and Page Title -->
        <!-- Dropdown Structure     -->
        <ul id="navdrop" class="dropdown-content">
          <li><a href="/">Home</a></li>
          <li><a href="/custom/">Custom Slug</a></li>
          <li><a href="/recent/">Recent Slugs</a></li>
        </ul>    
        <nav class="blue" role="navigation">
            <div class="nav-wrapper container">
                <a href="/" id="logo-container" class="brand-logo">TxMoo.se</a>
                <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                    <li><a class="dropdown-button" href="#!" data-activates="navdrop" data-beloworigin="true" data-constrainwidth="false" ><i class="material-icons">menu</i></a></li>
                </ul>
                <ul id="nav-mobile" class="side-nav">
                    <li><a href="/"><i class="material-icons">home</i>Home</a></li>
                    <li><a href="/custom/"><i class="material-icons">input</i>Custom</a></li>
                    <li><a href="/recent/"><i class="material-icons">list</i>Recent</a></li>
                </ul>
            </div>
        </nav>
        <div class="section no-pad-bot" id="index-banner">
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        
        <!-- JS  -->
        <script type="text/javascript" src="{% static 'material/js/jquery.datetimepicker.js' %}"></script>
        <script type="text/javascript" src="{% static 'material/js/jquery.formset.js' %}"></script>
        <script type="text/javascript" src="{% static 'material/js/materialize.js' %}"></script>
        <script type="text/javascript" src="{% static 'material/js/materialize.forms.js' %}"></script>
    </body>
</html>

web_front/templates/web_front/create.html
{% extends 'web_front/base.html' %}
{% block content %}
        {% load material_form %}

        <br><br>
        <h1 class="header center red-text">TxMoo.se URL Shortener</h1>
        <br><br>

        <div class="container" class="valign-wrapper" class="card-panel hoverable">
            <form action="/" method="post" class="valign">
                {% csrf_token %}
                {% form form=form %}{% endform %}
                <input type="submit" class="btn btn-primary btn-lg" value="Shorten it!" />
            </form>
        </div>
{% endblock %}

web_front/templates/web_front/detail.html
{% extends 'web_front/base.html' %}
{% block content %}
    <div class="container" class="valign-wrapper">
        <h3 class="header center red-text">{{ slug }}</h3>
        
          <div class="card-panel" class="z-depth-5">
            <ul>
              <li>slug => {{ slug.slug }}</li>
              <li>target url => {{ slug.target_url }}</li>
              <li>create date => {{ slug.create_date }}</li>
              <li>hit count => {{ slug.hit_count }}</li>
            </ul>
          </div>
    </div>
{% endblock %}

web_front/templates/web_front/recent.html
{% extends 'web_front/base.html' %}
{% block content %}
  <div class="container" class="valign-wrapper">
    <h1 class="header center red-text">{{slug_list|length}} most recent slugs created</h1>
      <ul class="collapsible popout" data-collapsible="accordion">
        {% for slug in slug_list %}
          <li>
            <div class="collapsible-header">{{ slug.slug }}</div>
            <div class="collapsible-body" style="display: block;">
              <p><a href="{% url 'web_front:detail' slug.slug %}">{{ slug.site_title }}</a></p>
            </div>
          </li>
        {% endfor %}
      </ul>
  </div>
{% endblock %}